### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Folcky** [hawley577/Inkscape-Rounded-Corners#6]
Traceback (most recent call last):
  File "RoundedCorners.py", line 406, in <module>
    e.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "RoundedCorners.py", line 224, in effect
    succeededRounding = self.MakeRound(node) or succeededRounding
  File "RoundedCorners.py", line 380, in MakeRound
    succeeded = self.RoundCorner(cursorIndex, (n+2) % npLen, (n+3) % npLen, (n+4) % npLen) or succeeded
  File "RoundedCorners.py", line 300, in RoundCorner
    multiplier = r/p0Dist
ZeroDivisionError: float division by zero

**Comment by hawley577** [comment]
I just fixed this error.  Please let me know if anything else goes wrong.
