### ISSUE TITLE
global name 'false' is not defined

### ISSUE THREAD

**Issue by Lzrnk** [hawley577/Inkscape-Rounded-Corners#7]
Traceback (most recent call last):
  File "RoundedCorners.py", line 437, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "RoundedCorners.py", line 240, in effect
    succeededRounding = self.MakeRound(node) or succeededRounding
  File "RoundedCorners.py", line 411, in MakeRound
    succeeded = self.RoundCorner(cursorIndex, (n+2) % npLen, (n+3) % npLen, (n+4) % npLen) or succeeded
  File "RoundedCorners.py", line 323, in RoundCorner
    return false
NameError: global name 'false' is not defined
Should be "False" not "false"

**Comment by hawley577** [comment]
So sorry.  I should have tested the previous commit.   Code is back to a working state now.
